### ISSUE TITLE
lnutil.py IncompatibleOrInsaneFeatures: not all transitive dependencies are set

### ISSUE THREAD

**Issue by mercurytoxic** [spesmilo/electrum#6559]
Using version 4.0.1.r14.gc66c54a25

```
$ electrum --testnet

E | gui.qt.ElectrumGui | 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/__init__.py", line 286, in start_new_window
    window = self._create_window_for_wallet(wallet)
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/__init__.py", line 233, in _create_window_for_
    w = ElectrumWindow(self, wallet)
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 201, in __init__
    self.send_tab = self.create_send_tab()
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 1385, in create_send_tab
    self.invoice_list = InvoiceList(self)
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/invoice_list.py", line 76, in __init__
    self.update()
  File "/usr/lib/python3.8/site-packages/electrum/gui/qt/invoice_list.py", line 101, in update
    for idx, item in enumerate(self.parent.wallet.get_invoices()):
  File "/usr/lib/python3.8/site-packages/electrum/wallet.py", line 743, in get_invoices
    out.sort(key=lambda x:x.time)
  File "/usr/lib/python3.8/site-packages/electrum/wallet.py", line 743, in <lambda>
    out.sort(key=lambda x:x.time)
  File "/usr/lib/python3.8/site-packages/electrum/invoices.py", line 179, in time
    return self._lnaddr.date
  File "/usr/lib/python3.8/site-packages/electrum/invoices.py", line 155, in _lnaddr
    self.__lnaddr = lndecode(self.invoice)
  File "/usr/lib/python3.8/site-packages/electrum/lnaddr.py", line 447, in lndecode
    validate_features(features)
  File "/usr/lib/python3.8/site-packages/electrum/lnutil.py", line 1039, in validate_features
    raise IncompatibleOrInsaneFeatures("not all transitive dependencies are set")
electrum.lnutil.IncompatibleOrInsaneFeatures: not all transitive dependencies are set
```

![2020-09-06-235035_1920x1080_scrot](https://user-images.githubusercontent.com/739809/92327298-f63cd380-f09b-11ea-9731-5fa995c823f8.png)

**Comment by SomberNight** [comment]
Do you know what invoice triggers this?

When/how did it start happening? E.g. did you paste an invoice, it crashed, and now you can't even open the wallet now?

**Comment by SomberNight** [comment]
I don't see how such an invoice could have been saved into the wallet in the first place :/

**Comment by mercurytoxic** [comment]
> When/how did it start happening?

Not sure. Can't remember.

> Do you know what invoice triggers this?

No. Can I figure this out from the wallet file list of invoices?

<b>$cat wallet | jq -r '.invoices'</b>
```yaml
{
  "1a2da100b9ee73e40e597291ac651e1e9c0f8ded3c345f0568bf74d10f62f41d": {
    "amount_msat": 800000000,
    "invoice": "lntb8m1p0gqkqypp5rgk6zq9eaee7grjew2g6ceg7r6wqlr0d8s697ptgha6dzrmz7swsdquveex7mfqv4kx2cm5wf6k6grjv4jqcqzpgxqzjcrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjxyc7gqqqagqqyqqqqlgqqqqqqgq9qnu3d473fpklmmdxlcrv5r2kdqkkxldx7rtusf5z0lkwc6zhnqn7sq9q0xanfhu5synuyalc6jj0z9c3cuxdemly3lvsg2af6u2g2p3cpwkrfx0",
    "type": 2
  },
  "27108691096ba1e97dd44496099a71bedb98c3ac85875a8a3ebcdf4359923d49": {
    "amount_msat": 100000000,
    "invoice": "lntb1m1pwmze82pp5yuggdygfdws7jlw5gjtqnxn3hmde3savskr44z37hn05xkvj84ysdqqxqrrssrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cng955ecqqqrsqqqqqqqlgqqqqqeqqjqrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmj9etkvqqqacqqqqqqqlgqqqqqeqqjqvp77k8gczutqqkn7sh98j52hdazdqm8gl4e8akkhvlad6yqxe6qzf2vznjed8n42g6esaw5zyq7lfj634k30vkvkn8p9wzv920z56nqp4vt9cd",
    "type": 2
  },
  "2c71bb3b1420fe7101ae31b027a90af18f4c728c2fa360eedd458c4a61d418ba": {
    "amount_msat": 3005100000,
    "invoice": "lntb30051u1pwahx2rpp593cmkwc5yrl8zqdwxxcz02g27x85cu5v973kpmkagkxy5cw5rzaqdy2xysyymr0vd4kzcmrd9hx7tpqxysy2umswfjhxum0yppk76twypgxzmnwvykzqvfq2d3kzmrpyppks6tsypr8yctswp6kxcmfdehjcgp3ypyxzmrxypsjq4r0dcsx7e3qgdhkven9v5cqp29qy9qqqdu2m37uwcdfahlfsqp55mzrvdk7sj0ay0849msn93h4s3zz3p0xpl30n2wdv0ksfpmyygqdka3grrfg3h0mle9umxc3c93dfdjhsjvsqul4h6u",
    "type": 2
  },
  "558189352b43877185e394fa6a39dccf": {
    "amount_sat": 100000000,
    "bip70": null,
    "exp": 0,
    "id": "558189352b43877185e394fa6a39dccf",
    "message": "Nayuta on OnePlus6T",
    "outputs": [
      [
        0,
        "tb1q75ddrxezxdq04z8v975kvkjs05hxjdvv5w7n9f",
        100000000
      ]
    ],
    "requestor": null,
    "time": 1575947747,
    "type": 0
  },
  "5e2e81b65c1e1250f46e8437f7a996d6": {
    "amount_sat": 10287,
    "bip70": null,
    "exp": 0,
    "id": "5e2e81b65c1e1250f46e8437f7a996d6",
    "message": "BTCPAY",
    "outputs": [
      [
        0,
        "tb1qvck3f7rh0ullxd0np6s0syhscp9asvkppneqjy",
        10287
      ]
    ],
    "requestor": null,
    "time": 1581136478,
    "type": 0
  },
  "6094937250ddcfe80e4263c482a2f1e4": {
    "amount_sat": 100000000,
    "bip70": null,
    "exp": 0,
    "id": "6094937250ddcfe80e4263c482a2f1e4",
    "message": "to mycelium on OnePlus6T",
    "outputs": [
      [
        0,
        "tb1qjumz5q9kvdnyv8xlg8tqvxaenczg3zfkm97k0c",
        100000000
      ]
    ],
    "requestor": null,
    "time": 1582033706,
    "type": 0
  },
  "8c2206c066793a046b0a4456dad9c4d3f20534841bbea1026df1e9ce187eeab4": {
    "amount_msat": 2000000000,
    "invoice": "lntb20m1p0re4tapp53s3qdsrx0yaqg6c2g3td4kwy60eq2dyyrwl2zqnd785uuxr7a26qdpqveex7mfqv4kx2cm5wf6k6gr0dcs8yetycqzpgxqzjcrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjxyc7gqqqagqqyqqqqlgqqqqqqgq9qvf264uj4lp2dxej38dcuhjn8wx94ewm39ryk3f0u390t6tzsgv0zgtxvykqwhnjj9n5lpd6dnds6mt37c3njtwet0lsjzumlvlyn6jqqmmppyu",
    "type": 2
  },
  "9eaa656e190dd926bfbd93fe571bbbada208ff0e78887efccae808301f76aae0": {
    "amount_msat": 1000000000,
    "invoice": "lntb10m1pwmg4rnpp5n64x2msephvjd0aaj0l9wxam4k3q3lcw0zy8alx2aqyrq8mk4tsqdquveex7mfqv4kx2cm5wf6k6grjv4jqcqzynxqyz5vqrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjxpt4yqqpysqqqqqqqlgqqqqqqgq9qnccd3qyef2xg5ypqker568vlj2rwkw9az0x09c7pykh9myxq4jt9n4mhwl3zwh0vzpa2pfk2ut507ncxyh5hd0jawjnx5u9xjccsdgqptgak29",
    "type": 2
  },
  "c53bfa5ecfe5ae2cca849d3f19adbdeb4b66b91ace497ec51e16fc3c5a9545ce": {
    "amount_msat": 4000000000,
    "invoice": "lntb40m1p09yygfpp5c5al5hk0ukhzej5yn5l3ntdaad9kdwg6eeyha3g7zm7rck54gh8qdquveex7mfqv4kx2cm5wf6k6grjv4jqcqzpgxqyz5vqsp5tmxp5seph24yjepjgzva6jnxrh8w305787qmx8fx3ex2lywf9d3s9qy9qsqkdmjtsqmpt3sdka02nmtdgx9v68ezlelcfdrh748wuuwen427qy4cjzhljp63fhcn0mg6fm8eyqz4xp3kpy2egj9e7j9rjg92a45dtsp5c4ztw",
    "type": 2
  },
  "d8e85f3630cda82e71528b6f9866306ba69ff5a7a20e592a9ed3d111609b8f7a": {
    "amount_msat": 10000000000,
    "invoice": "lntb100m1pwmg55rpp5mr597d3sek5zuu2j3dhese3sdwnflad85g89j25760g3zcym3aaqdquveex7mfqv4kx2cm5wf6k6grjv4jqcqzynxqyz5vqy7jtwlvwcrtfnlftfrlxfaj3pzv345t7jmqw8dckptxvqa6wvvyy6vq6r2wjkzm5ev5vwp6a24nw8x9avpz28kk4rlxm75nvp5yxfsgpgr28jz",
    "type": 2
  },
  "e1ff39434ffa95c47aace7ef76da1d4e": {
    "amount_sat": 10269,
    "bip70": null,
    "exp": 0,
    "id": "e1ff39434ffa95c47aace7ef76da1d4e",
    "message": "BTCPAY",
    "outputs": [
      [
        0,
        "tb1qlnljzq2xwczkhhkchsa69wavazwc7fz6ln2guv",
        10269
      ]
    ],
    "requestor": null,
    "time": 1581138485,
    "type": 0
  },
  "e91b6af25a80d4ed104945f7bbc42456442de4dfe2c1fe5c3a0ad2dd2e972cf5": {
    "amount_msat": 278000,
    "invoice": "lntb2780n1p0r3w89pp5aydk4uj6sr2w6yzfghmmh3py2ezzmexlutqluhp6ptfd6t5h9n6sdqugeex7mfqv4kx2cm5wf6k6grjv4jqcqzpgxqzjcrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cngxyca5qqqhsqqqqqqqlgqqqqqeqqjqa5w2v4d4n2pz962a5hercp9nr3xhhgfwhzclanqrylteytr8zuzxlyt9q5a8a5pqk0htazfr63y52l9lrx58cm9tc4ucr3dcmy9mmygqfcn4sg",
    "type": 2
  },
  "f2077ea51eed82e5da9807989a4b08e2e9c02f79aca1da48748ab92971686d81": {
    "amount_msat": 2000000000,
    "invoice": "lntb20m1pw73azepp57grhafg7akpwtk5cq7vf5jcgut5uqtme4jsa5jr532ujjutgdkqsdquveex7mfqv4kx2cm5wf6k6grjv4jqcqzynxqyz5vqrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjxy4svqqqesqqqqqqqlgqqqqqqgq9qzfy5wjvmqzxglfeck28rhrfrx5lj6g5zx2ndgy4j8xt0q794rzax56xv9fgjzetwuxqernmamtfug22qnnv6f60agczcymnfqd3l0agqh06kvn",
    "type": 2
  }
}
```
